/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

/**
 * @author Sefa + my baby Chris
 * version 0.0
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
